### PR TITLE
Fix Issue #72: Update "MIPLIB 2017" to "MIP relaxations"

### LINKED ISSUE #72: Update "MIPLIB 2017" to "MIP Relaxations"
For consistency with the paper.

### PR DESCRIPTION
**Pull request by dapplegate**
Fixes #72

As part of this change, switched from using the result of unzipping collections.zip as the source for un-preprocessed instances to explicitly extracting the "MIP relaxations" instances. To keep this clean, created a "collect_mip_relaxations.sh" script instead of just asking the reader to unzip collections.zip.

Tested by running manually.

### CODE REVIEW

File: benchmarking/collect_mip_relaxations.sh [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+readarray -t instances < <(egrep -v '^#' "${INSTANCE_FILE}")
+declare -a filenames
+for instance in "${instances[@]}"; do
+  filenames+=("${instance}.mps.gz")
+done
+
+wget --directory-prefix="${TEMP_DIR}" \
+  https://miplib.zib.de/downloads/collection.zip || exit 1
+
+unzip -d "${DEST_DIR}" "${TEMP_DIR}/collection.zip" "${filenames[@]}"
```
Comment (mlubin) [inline benchmarking/collect_mip_relaxations.sh:46]: Perhaps delete "${TEMP_DIR}/collection.zip" at the end?

**Review by mlubin — APPROVED** [review]

File: benchmarking/collect_mip_relaxations.sh (hunk 1 above)
Comment (dapplegate) [reply benchmarking/collect_mip_relaxations.sh]: Done.
